apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "acm-aws-cluster.fullname" . }}-aws-credentials
stringData:
  aws_access_key_id: {{ .Values.aws_id }} 
  aws_secret_access_key: {{ .Values.aws_key }}