apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
  name: {{ template "acm-aws-cluster.fullname" . }}-ocp4.4.0-x86-64
spec:
  releaseImage: 'quay.io/openshift-release-dev/ocp-release:4.4.0-x86_64'