apiVersion: v1
kind: Secret
metadata:
  name: {{ template "acm-aws-cluster.fullname" . }}-docker-pull-secret
stringData:
  .dockerconfigjson: {{ .Values.docker_pull_secret | toJson | toJson }}
type: kubernetes.io/dockerconfigjson