
{{ $myDict := .Values.install_config }}

{{- if .Values.fullnameOverride }}
{{ $_ := set $myDict.metadata "name" (.Values.fullnameOverride | trunc 63 | trimSuffix "-") }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{ $_ := set $myDict.metadata "name" (.Release.Name | trunc 63 | trimSuffix "-") }}
{{- else }}
{{ $_ := set $myDict.metadata "name" (printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-") }}
{{- end }}
{{- end }}

 
{{ $_ := set $myDict "baseDomain" .Values.baseDomain }}  
{{ $_ := set $myDict.platform.aws "region" .Values.region }}  
{{ $_ := set $myDict "sshKey" .Values.sshPubKey }}  

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "acm-aws-cluster.fullname" . }}-install-config
type: Opaque
data:
  install-config.yaml: {{ $myDict | toPrettyJson | b64enc }}
