apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - ceph-mon.ceph.svc.cluster.local:6789
    pool: kube
    image: ceph-rbd-pv-test
    user: kube
    secretRef:
      name: ceph-kube-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
