apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kiali-ossm
spec:
  upgradeStrategy: Default
---  
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace