apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      containers:
        -
          name: traefik-ingress-lb
          image: traefik
          args:
            - '--web'
            - '--kubernetes'
            - '--entryPoints=Name:http Address::8081'
            - '--defaultentrypoints=http'
          ports:
            -
              name: http
              hostPort: 8081
              containerPort: 8081
              protocol: TCP
            -
              name: admin
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      serviceAccountName: traefik
      serviceAccount: traefik