apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: grafana-operator
spec:
  upgradeStrategy: Default
---  
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
spec:
  channel: v5
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  config:
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
      limits: {}