# ---
# apiVersion: operators.coreos.com/v1
# kind: OperatorGroup
# metadata:
#   name: code-ready-workspaces
#   namespace: code-ready-workspaces 
# spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "code-ready-workspaces"
  namespace: "code-ready-workspaces" 
spec:
  channel: final
  installPlanApproval: Automatic
  name: codeready-workspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: crwoperator.v1.2.2
---