apiVersion: operator.openshift.io/v1alpha1
kind: CertManager
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true   
spec:
  controllerConfig:                                
    overrideArgs:
      - '--dns01-recursive-nameservers-only'       
      - '--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53'