      
applications: 

  openshift-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-config
    source:
      path: misc4.0/etl/etl4/components/openshift-config

  openshift-virtualization:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-cnv
    source:
      path: misc4.0/etl/etl4/components/openshift-virtualization

  web-terminal-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-operators
    source:
      path: misc4.0/etl/etl4/components/web-terminal-operator

  trident-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: netapp-trident
    source:
      path: misc4.0/etl/etl4/components/trident-operator

  trident-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: netapp-trident
    source:
      path: misc4.0/etl/etl4/components/trident-configuration      

  hyperconverged-instance:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: openshift-cnv
    source:
      path: misc4.0/etl/etl4/components/hyperconverged-instance  

  kube-ops-view:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: kube-ops-view
    source:
      path: misc4.0/etl/etl4/components/kube-ops-view   


# OpenShift ServiceMesh

  openshift-servicemesh:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-servicemesh-operator
    source:
      path: misc4.0/etl/etl4/components/openshift-servicemesh

  servicemesh-control-plane:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: istio-system
    source:
      path: misc4.0/etl/etl4/components/servicemesh-control-plane

  # servicemesh-configuration:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '25'
  #   destination:
  #     namespace: istio-system
  #   source:
  #     path: misc4.0/etl/etl4/components/servicemesh-configuration          


                          