---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: redis 
spec: 
  targetNamespaces:
    - redis
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "redis"
spec:
  channel: production
  installPlanApproval: Automatic
  name: redis-enterprise-operator-cert
  source: certified-operators
  sourceNamespace: openshift-marketplace
---
