
apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec
spec:
  nodes: 3
  persistentSpec:
    enabled: true
  uiServiceType: ClusterIP
  username: demo@redislabs.com
  redisEnterpriseNodeResources:
    limits:
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  redisEnterpriseImageSpec:
    imagePullPolicy: IfNotPresent
    repository: redislabs/redis
    versionTag: 5.4.14-31.rhel7-openshift     
  activeActive: # edit values according to your cluster
    apiIngressUrl:  redis-api.apps.cluster-c5ed.sandbox753.opentlc.com
    dbIngressSuffix: -redis-db.apps.cluster-c5ed.sandbox753.opentlc.com
    method: openShiftRoute
  rackAwarenessNodeLabel: failure-domain.beta.kubernetes.io/zone     