---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: self-signer
spec:
  selfSigned: {}
---
  # Generate a RootCA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: rootca
spec:
  secretName: rootca
  issuerRef:
    name: self-signer
  commonName: "ca.self-signer.cert-manager"
  isCA: true
---
  # Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: internal-issuer
spec:
  ca:
    secretName: rootca