apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,ServerSideApply=true  
spec:
  routeAdmission:
    namespaceOwnership: InterNamespaceAllowed
    wildcardPolicy: WildcardsAllowed