apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: servicemesh
spec:
  labelSelector:
    matchLabels:
      servicemesh: "true"
  templates:  
    - objectTemplate: |
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: user-workload-access
          namespace: {{ .Name }}
        spec:
          ingress:
          - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: monitoring
          podSelector: {}
          policyTypes:
          - Ingress
      excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas          
    - objectTemplate: |
        apiVersion: monitoring.coreos.com/v1
        kind: PodMonitor
        metadata:
          name: istio-proxies-monitor
          namespace: {{ .Name }}
        spec:
          selector:
            matchExpressions:
            - key: istio-prometheus-ignore
              operator: DoesNotExist
          podMetricsEndpoints:
          - path: /stats/prometheus
            interval: 30s
            relabelings:
            - action: keep
              sourceLabels: [__meta_kubernetes_pod_container_name]
              regex: "istio-proxy"
            - action: keep
              sourceLabels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape]
            - action: replace
              regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
              replacement: '[$2]:$1'
              sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_port,__meta_kubernetes_pod_ip]
              targetLabel: __address__
            - action: replace
              regex: (\d+);((([0-9]+?)(\.|$)){4})
              replacement: $2:$1
              sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_port,__meta_kubernetes_pod_ip]
              targetLabel: __address__
            - action: labeldrop
              regex: "__meta_kubernetes_pod_label_(.+)"
            - sourceLabels: [__meta_kubernetes_namespace]
              action: replace
              targetLabel: namespace
            - sourceLabels: [__meta_kubernetes_pod_name]
              action: replace
              targetLabel: pod_name
            - action: replace
              replacement: istio-system/main
              targetLabel: mesh_id
      excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas                                