apiVersion: v1
baseDomain: sandbox1250.opentlc.com
compute:
- name: worker
  platform: {}
  replicas: 4
  hyperthreading: Enabled
controlPlane:
  name: master
  platform: {}
  replicas: 3
  hyperthreading: Enabled
metadata:
  name: raffa2
networking:
  clusterNetworks:
  - cidr: 10.132.0.0/14
    hostPrefix: 23
  machineCIDR: 10.1.0.0/16
  serviceNetwork: 
    - 172.31.0.0/16
  type: OpenShiftSDN
platform:
  aws:
    region: us-east-2
pullSecret: ${pull_secret}
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDtty9+Qton+j31GmZGakLqlk4tPuo/MFnWI9bYKXUhxc2w0AA99mw0KbO4VTP0Y5LeEbXE0aCls13TseH2CtoFUhnDSxxWM9aW9C4vXDMfd1buTPaDJMLaKOtynzu34Hkm7P7wnArw3Yr9mWoeTgTRWg38XiyKeh9z51L/TQden7NW2znaQCav8QWZGLm0LyiJWjMif5AqPBYee/EA3cugjU7ZFpCRvpxCarjCT+3jAAV702IynYsqBf+4mD7UBG5GU7zbmYJtmXIzcgBge9vyfSKhhXvioKkT9Y4NB+qBg9dJ0LJKaU+zIzHqwF7T07i3nQwnBG885amDyRHPDAdj rspazzol
