apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: kubesan
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: kubesan.gitlab.io
deletionPolicy: Delete
