apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - manually-installed-external-dns.yaml
  - namespace.yaml
  - rfc2136-tsig-secret.yaml
  - dns-endpoint-crd.yaml