apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: trilio-system
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: k8s-triliovault
spec:
  channel: 4.0.x
  installPlanApproval: Automatic
  name: k8s-triliovault
  source: certified-operators
  sourceNamespace: openshift-marketplace
