apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-controller-manager-config
  labels:
    {{- include "spire.labels" . | nindent 4 }}  
data:
  spire-controller-manager-config.yaml: |
    apiVersion: spire.spiffe.io/v1alpha1
    kind: ControllerManagerConfig
    metrics:
      bindAddress: 127.0.0.1:8082
    healthProbe:
      bindAddress: 127.0.0.1:8083
    leaderElection:
      leaderElect: true
      resourceName: 98c9c988.spiffe.io
      resourceNamespace: {{ .Release.Namespace }}
    clusterName: cluster1
    trustDomain: cluster1.demo
    ignoreNamespaces:
      - kube-system
      - kube-public
      - {{ .Release.Namespace }}
      - local-path-storage
      - openshift-apiserver 
      - openshift-apiserver-operator
      - openshift-authentication   
      - openshift-authentication-operator
      - openshift-cloud-controller-manager            
      - openshift-cloud-controller-manager-operator   
      - openshift-cloud-credential-operator            
      - openshift-cloud-network-config-controller       
      - openshift-cluster-csi-drivers           
      - openshift-cluster-machine-approver    
      - openshift-cluster-node-tuning-operator   
      - openshift-cluster-samples-operator  
      - openshift-cluster-storage-operator   
      - openshift-cluster-version      
      - openshift-config          
      - openshift-config-managed     
      - openshift-config-operator   
      - openshift-console       
      - openshift-console-operator   
      - openshift-console-user-settings     
      - openshift-controller-manager 
      - openshift-controller-manager-operator  
      - openshift-dns             
      - openshift-dns-operator 
      - openshift-etcd      
      - openshift-etcd-operator  
      - openshift-host-network    
      - openshift-image-registry      
      - openshift-infra  
      - openshift-ingress      
      - openshift-ingress-canary    
      - openshift-ingress-operator   
      - openshift-insights   
      - openshift-kni-infra 
      - openshift-kube-apiserver    
      - openshift-kube-apiserver-operator  
      - openshift-kube-controller-manager
      - openshift-kube-controller-manager-operator  
      - openshift-kube-scheduler        
      - openshift-kube-scheduler-operator  
      - openshift-kube-storage-version-migrator
      - openshift-kube-storage-version-migrator-operator  
      - openshift-machine-api                
      - openshift-machine-config-operator  
      - openshift-marketplace        
      - openshift-monitoring      
      - openshift-multus            
      - openshift-network-diagnostics      
      - openshift-network-operator    
      - openshift-node            
      - openshift-nutanix-infra     
      - openshift-oauth-apiserver     
      - openshift-openstack-infra  
      - openshift-operator-lifecycle-manager     
      - openshift-operators                 
      - openshift-ovirt-infra       
      - openshift-ovn-kubernetes     
      - openshift-route-controller-manager     
      - openshift-security-profiles   
      - openshift-service-ca        
      - openshift-service-ca-operator      
      - openshift-user-workload-monitoring    
      - openshift-vsphere-infra      





