apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: ProfileRecording
metadata:
  name: oracle-rac
spec:
  kind: SelinuxProfile
  recorder: logs
  podSelector:
    matchLabels:
      app: oracle-rac