apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-rac-disk1
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 30Gi
  storageClassName: ontap-san
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-rac-disk2
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 30Gi
  storageClassName: ontap-san            