apiVersion: v1
kind: ConfigMap
metadata:
  name: response-files
data:
  grid.rsp: | 
    oracle.install.responseFileVersion=/oracle/install/rspfmt_crsinstall_response_schema_v21.0.0
    INVENTORY_LOCATION=/u01/app/oraInventory
    oracle.install.option=CRS_CONFIG
    ORACLE_BASE=/u01/app/grid
    oracle.install.asm.OSDBA=asmdba
    oracle.install.asm.OSOPER=asmoper
    oracle.install.asm.OSASM=asmadmin
    oracle.install.crs.config.scanType=LOCAL_SCAN
    oracle.install.crs.config.SCANClientDataFile=
    oracle.install.crs.config.gpnp.scanName=racnodepc1-scan
    oracle.install.crs.config.gpnp.scanPort=1521
    oracle.install.crs.config.ClusterConfiguration=STANDALONE
    oracle.install.crs.config.configureAsExtendedCluster=false
    oracle.install.crs.config.clusterName=racnodep1-c
    oracle.install.crs.config.gpnp.configureGNS=false
    oracle.install.crs.config.autoConfigureClusterNodeVIP=false
    oracle.install.crs.config.gpnp.gnsOption=CREATE_NEW_GNS
    oracle.install.crs.config.gpnp.gnsClientDataFile=
    oracle.install.crs.config.gpnp.gnsSubDomain=
    oracle.install.crs.config.gpnp.gnsVIPAddress=
    oracle.install.crs.config.sites=
    oracle.install.crs.config.clusterNodes=racnodep1:racnodep1-vip,racnodep2:racnodep2-vip
    oracle.install.crs.config.networkInterfaceList=eth1:172.20.1.0:1,eth2:192.168.100.0:2
    oracle.install.crs.config.storageOption=FLEX_ASM_STORAGE
    oracle.install.crs.exascale.vault.name=
    oracle.install.crs.config.sharedFileSystemStorage.votingDiskLocations=
    oracle.install.crs.config.sharedFileSystemStorage.ocrLocations=
    oracle.install.asm.ClientDataFile=               	
    oracle.install.crs.config.useIPMI=false
    oracle.install.crs.config.ipmi.bmcBinpath=
    oracle.install.crs.config.ipmi.bmcUsername=
    oracle.install.crs.config.ipmi.bmcPassword=
    oracle.install.asm.SYSASMPassword=
    oracle.install.asm.diskGroup.name=DATA
    oracle.install.asm.diskGroup.redundancy=EXTERNAL
    oracle.install.asm.diskGroup.AUSize=4
    oracle.install.asm.diskGroup.FailureGroups=
    oracle.install.asm.diskGroup.disksWithFailureGroupNames=/dev/asm-disk1,,/dev/asm-disk2,
    oracle.install.asm.diskGroup.disks=/dev/asm-disk1,/dev/asm-disk2
    oracle.install.asm.diskGroup.quorumFailureGroupNames=
    oracle.install.asm.diskGroup.diskDiscoveryString=/dev/*
    oracle.install.asm.monitorPassword=
    oracle.install.asm.configureAFD=false
    oracle.install.crs.configureRHPS=false
    oracle.install.crs.config.ignoreDownNodes=false
    oracle.install.crs.configureGIMR=false
    oracle.install.crs.configureRemoteGIMR=false
    oracle.install.crs.RemoteGIMRCredFile=
    oracle.install.asm.configureGIMRDataDG=false
    oracle.install.asm.gimrDG.name=
    oracle.install.asm.gimrDG.redundancy=
    oracle.install.asm.gimrDG.AUSize=1
    oracle.install.asm.gimrDG.FailureGroups=
    oracle.install.asm.gimrDG.disksWithFailureGroupNames=
    oracle.install.asm.gimrDG.disks=
    oracle.install.asm.gimrDG.quorumFailureGroupNames=
    oracle.install.config.managementOption=NONE
    oracle.install.config.omsHost=
    oracle.install.config.omsPort=0
    oracle.install.config.emAdminUser=
    oracle.install.config.emAdminPassword=
    oracle.install.crs.rootconfig.executeRootScript=false
    oracle.install.crs.rootconfig.configMethod=ROOT
    oracle.install.crs.rootconfig.sudoPath=
    oracle.install.crs.rootconfig.sudoUserName=
    oracle.install.crs.config.batchinfo=
    oracle.install.crs.deleteNode.nodes=  