apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-oadp
spec:
  channel: stable
  installPlanApproval: Automatic
  name: redhat-oadp-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-oadp
spec:
  targetNamespaces:
    - openshift-adp