apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netapp-trident

resources:
  - namespace.yaml
  - trident.netapp.io_tridentorchestrators_crd_post1.16.yaml

helmCharts:

  - name: trident-operator
    releaseName: netapp-trident
    namespace: netapp-trident
    repo: https://netapp.github.io/trident-helm-chart
