apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - endpoints.yaml
  - ippool.yaml
  - l2advertisement.yaml
  - lb-service.yaml
  - namespace.yaml
  - vms.yaml
  - next-dhcp-configmap.yaml
  - next-dhcp-deployment.yaml
  - multus-service.yaml
  #- loxilb.yaml
  #- kube-loxilb.yaml
  #- gravity-dhcp-deployment.yaml