apiVersion: v1
kind: Service
metadata:
  name: vms-web
  annotations:
    metallb.universe.tf/address-pool: production-public-ips  
spec:
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer