apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true  
data:
  config.yaml: |
    enableUserWorkload: true