apiVersion: "operators.coreos.com/v1"
kind: "CatalogSourceConfig"
metadata:
  name: "service-mesh"
  namespace: "openshift-marketplace"
spec:
  csDisplayName: Red Hat Operators
  csPublisher: Red Hat
  targetNamespace: "openshift-operators" 
  packages: "elasticsearch-operator,servicemeshoperator,kiali-ossm,jaeger-product"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "elasticsearch-operator"
  namespace: "openshift-operators" 
spec:
  channel: "preview" 
  installPlanApproval: "Automatic"
  source: "service-mesh"
  sourceNamespace: "openshift-operators" 
  name: "elasticsearch-operator"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "jaeger-operator"
  namespace: "openshift-operators" 
spec:
  channel: "preview" 
  installPlanApproval: "Automatic"
  source: "service-mesh"
  sourceNamespace: "openshift-operators" 
  name: "jaeger-product"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "kiali-operator"
  namespace: "openshift-operators" 
spec:
  channel: "preview" 
  installPlanApproval: "Automatic"
  source: "service-mesh"
  sourceNamespace: "openshift-operators" 
  name: "kiali-ossm"  
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "service-mesh-operator"
  namespace: "openshift-operators" 
spec:
  channel: "1.0" 
  installPlanApproval: "Automatic"
  source: "service-mesh"
  sourceNamespace: "openshift-operators" 
  name: "servicemeshoperator"      