apiVersion: "operators.coreos.com/v1"
kind: "CatalogSourceConfig"
metadata:
  name: "service-mesh"
  namespace: "openshift-marketplace"
spec:
  csDisplayName: Red Hat Operators
  csPublisher: Red Hat
  targetNamespace: "openshift-operators" 
  packages: "servicemeshoperator"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "service-mesh-operator"
  namespace: "openshift-operators" 
spec:
  channel: "1.0" 
  installPlanApproval: "Automatic"
  source: "service-mesh"
  sourceNamespace: "openshift-operators" 
  name: "servicemeshoperator"