apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: metallb-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator-sub
spec:
  channel: stable
  name: metallb-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
