apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.prometheus.name }}
  namespace: {{ .Release.Namespace }}
spec:
  port:
    targetPort: proxy
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: prometheus-k8s
