apiVersion: v1
kind: Secret
metadata:
  name: tempo-tenant
stringData:
  endpoint: http://minio.openshift-tempo-instance.svc.cluster.local
  bucket: tempo
  access_key_id: tempo
  access_key_secret: tempotempo
type: Opaque