apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cert-utils-operator
  namespace: cert-utils-operator
spec:
  targetNamespaces:
  - cert-utils-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-utils-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: cert-utils-operator
  source: installed-community-cert-utils-operator
  sourceNamespace: cert-utils-operator
  startingCSV: cert-utils-operator.v0.0.1