apiVersion: triliovault.trilio.io/v1
kind: BackupPlan
metadata:
  name: ns-backupplan
spec:
  backupConfig:
    target:
      apiVersion: triliovault.trilio.io/v1	
      kind: Target    
      namespace: trilio-system
      name: trilio-s3-target