apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: servicemesh-operator
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemesh-operator
spec:
  channel: stable
  #installPlanApproval: Manual
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace