export OPENSHIFT_INSTALL_BASE_DOMAIN=raffa.xyz
export OPENSHIFT_INSTALL_CLUSTER_NAME=env1
export OPENSHIFT_INSTALL_PLATFORM=aws
export OPENSHIFT_INSTALL_PULL_SECRET_PATH=./pull-secret.json 
export OPENSHIFT_INSTALL_SSH_PUB_KEY_PATH=~/.ssh/sshkey-gcp.pub
export OPENSHIFT_INSTALL_AWS_REGION="us-east-1"