apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: s3-provider
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - 's3:*'
      effect: Allow
      resource: '*'
  secretRef:
    name: s3-provider
    namespace: s3-provider