kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: s3-buckets
provisioner: aws-s3.io/bucket
parameters:
  region: us-west-2
  secretName: s3-provider
  secretNamespace: s3-prvoider
reclaimPolicy: Delete