apiVersion: v1
kind: Service
metadata:
  annotations:
  name: {{ template "redis-proxy.fullname" . }}-envoy-proxy
spec:
  ports:
  - name: envoy-redis-tcp
    port: 6378
    protocol: TCP
    targetPort: envoy-redis-tcp
  type: LoadBalancer  
  selector:
    app.kubernetes.io/instance: {{ template "redis-proxy.fullname" . }}