---

ansible_user: openshift
ansible_become: True

deployment_type: openshift-enterprise
openshift_deployment_type: openshift-enterprise
openshift_master_cluster_method: native
openshift_master_cluster_hostname: "{{ groups.lb.0 }}"
openshift_master_cluster_public_hostname: "{{ groups.lb.0 }}"
openshift_master_default_subdomain: "apps.{{ env_id }}.{{ public_dns_domain }}"

#openshift_deployment_type: openshift-enterprise
openshift_release: v3.6
#openshift_master_default_subdomain: "apps.{{ env_id }}.{{ public_dns_domain }}"

# HTPASSWD Identity Provider
openshift_master_identity_providers:
 - 'name': 'htpasswd_auth'
   'login': 'true'
   'challenge': 'true'
   'kind': 'HTPasswdPasswordIdentityProvider'
   'filename': '/etc/origin/master/htpasswd'
   
openshift_master_htpasswd_users:
  admin: $apr1$7aiANAYb$TOUYVUqnBqBlD5AQEIMYw1   

openshift_hosted_logging_deploy: true
openshift_logging_es_pvc_size: 100Gi
openshift_logging_es_cluster_size: 3
openshift_logging_es_number_of_replicas: 2
openshift_logging_kibana_replica_count: 1
openshift_logging_es_nodeselector: 
  region: infra
openshift_logging_kibana_nodeselector: 
  region: infra
openshift_logging_curator_nodeselector: 
  region: infra

openshift_hosted_metrics_deploy: true
#openshift_hosted_metrics_storage_kind: dynamic
openshift_metrics_hawkular_nodeselector:
  region: infra
openshift_metrics_cassandra_nodeselector: 
  region: infra
openshift_metrics_heapster_nodeselector: 
  region: infra  
openshift_metrics_selector: "region=infra" 
openshift_hosted_metrics_storage_volume_size: 10Gi
openshift_metrics_hawkular_replicas: 2
openshift_metrics_cassandra_replicas: 3 

openshift_node_labels: "{{ openstack.metadata.node_labels}}"
openshift_node_kubelet_args:
  minimum-container-ttl-duration:
  - "10s"
  maximum-dead-containers-per-container:
  - "2"
  maximum-dead-containers:
  - "50"
  pods-per-core: 
  - '10'
  max-pods: 
  - '250'
  image-gc-high-threshold: 
  - '80'
  image-gc-low-threshold: 
  - '60'

osm_default_node_selector: 'region=primary'
osm_use_cockpit: true
osm_cockpit_plugins: 
- 'cockpit-kubernetes'
#create_users:
#  num_users: 5
#  prefix: 'rdu-user'
#  passwd_file: '/etc/origin/master/htpasswd'
#  password: 'rdu-sample'


openshift_docker_insecure_registries:
  - docker-registry.default.svc:5000
openshift_docker_options: "--log-driver=json-file --log-opt max-size=50m --log-opt max-file=100 --storage-opt dm.basesize=25G"

openshift_cloudprovider_kind: openstack
openshift_cloudprovider_openstack_auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
openshift_cloudprovider_openstack_username: "sa_casl_contrib"
openshift_cloudprovider_openstack_password: "UKyq9t752A73CfqD"
openshift_cloudprovider_openstack_domain_name: Default
openshift_cloudprovider_openstack_tenant_id: "{{ lookup('env','OS_PROJECT_ID') }}"
openshift_cloudprovider_openstack_tenant_name: "{{ lookup('env','OS_PROJECT_NAME') }}"
openshift_cloudprovider_openstack_region: "{{ lookup('env','OS_REGION_NAME') }}"
openshift_cloudprovider_openstack_lb_subnet_id: 89dc38ac-8e32-43ca-8861-da0509969769

# os_sdn_network_plugin_name: 'redhat/openshift-ovs-networkpolicy'
os_sdn_network_plugin_name: 'redhat/openshift-ovs-multitenant'

deployment_type: openshift-enterprise

openshift_disable_check: 
  - docker_storage
  - memory_availability
  - disk_availability
  
openshift_enable_service_catalog: false
openshift_template_service_broker_namespaces: 
  - openshift 
  
#cloudforms settings
openshift_cfme_install_app: true 

targetd_lvm_volume_group: vg-targetd
targetd_lvm_physical_volume: /dev/vdc
targetd_password: ciao
targetd_user: admin
targetd_iscsi_target: iqn.2003-01.org.example.mach1:1234
iscsi_provisioner_pullspec: raffaelespazzoli/iscsi-controller:0.0.1
iscsi_provisioner_default_storage_class: false

#gluster
openshift_storage_glusterfs_namespace: glusterfs 
openshift_storage_glusterfs_name: storage
openshift_storage_glusterfs_nodeselector: "region=infra"




