apiVersion: v1
kind: Template
labels:
  template: glusterfs
metadata:
  annotations:
    description: GlusterFS container deployment template
    tags: glusterfs
  labels:
    glusterfs: template
  name: glusterfs
objects:
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    annotations:
      description: Deploys the GlusterFS container
    labels:
      glusterfs: ds
    name: glusterfs-ds
  spec:
    template:
      metadata:
        labels:
          glusterfs: pod
          name: glusterfs
        name: glusterfs
      spec:
        nodeSelector: 
          gluster: ${GLUSTER_NODE_LABEL_VALUE}
        containers:
        - image: 172.30.201.40:5000/glusterfs/glusterfs:latest
          imagePullPolicy: Always
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - systemctl status glusterd.service
            initialDelaySeconds: 60
            timeoutSeconds: 3
          name: glusterfs
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - systemctl status glusterd.service
            initialDelaySeconds: 60
            timeoutSeconds: 3
          securityContext:
            capabilities: {}
            privileged: true
          volumeMounts:
          - mountPath: /var/lib/heketi
            name: glusterfs-heketi
          - mountPath: /run
            name: glusterfs-run
          - mountPath: /run/lvm
            name: glusterfs-lvm
          - mountPath: /etc/glusterfs
            name: glusterfs-etc
          - mountPath: /var/log/glusterfs
            name: glusterfs-logs
          - mountPath: /var/lib/glusterd
            name: glusterfs-config
          - mountPath: /dev
            name: glusterfs-dev
          - mountPath: /sys/fs/cgroup
            name: glusterfs-cgroup
          lifecycle: 
            postStart:
              exec: 
                command:
                - /usr/bin/bash 
                - /usr/bin/annotate-pod
        hostNetwork: true
        volumes:
        - hostPath:
            path: /var/lib/heketi
          name: glusterfs-heketi
        - name: glusterfs-run
        - hostPath:
            path: /run/lvm
          name: glusterfs-lvm
        - hostPath:
            path: /etc/glusterfs
          name: glusterfs-etc
        - hostPath:
            path: /var/log/glusterfs
          name: glusterfs-logs
        - hostPath:
            path: /var/lib/glusterd
          name: glusterfs-config
        - hostPath:
            path: /dev
          name: glusterfs-dev
        - hostPath:
            path: /sys/fs/cgroup
          name: glusterfs-cgroup
parameters:
- description: The value of the 'gluster' node label to be used as a selector for this deployment
  displayName: Value of the 'gluster' node label
  name: GLUSTER_NODE_LABEL_VALUE
  required: true