apiVersion: v1
kind: Template
labels:
  template: heketi
metadata:
  annotations:
    description: Heketi service deployment template
    tags: glusterfs,heketi
  labels:
    glusterfs: heketi-template
  name: heketi
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes Heketi service
    labels:
      glusterfs: heketi-service
    name: heketi
  spec:
    ports:
    - name: heketi
      port: 8080
      targetPort: 8080
    selector:
      name: heketi
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      glusterfs: heketi-route
    name: heketi
  spec:
    to:
      kind: Service
      name: heketi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy Heketi
    labels:
      glusterfs: heketi-dc
    name: heketi
  spec:
    replicas: 1
    selector:
      name: heketi
    template:
      metadata:
        labels:
          glusterfs: heketi-pod
          name: heketi
        name: heketi
      spec:
        containers:
        - env:
          - name: HEKETI_USER_KEY
            value: ${HEKETI_USER_KEY}
          - name: HEKETI_ADMIN_KEY
            value: ${HEKETI_ADMIN_KEY}
          - name: HEKETI_EXECUTOR
            value: kubernetes
          - name: HEKETI_FSTAB
            value: /var/lib/heketi/fstab
          - name: HEKETI_SNAPSHOT_LIMIT
            value: "14"
          - name: HEKETI_KUBE_CERTFILE
            value: ${HEKETI_KUBE_CERTFILE}
          - name: HEKETI_KUBE_INSECURE
            value: ${HEKETI_KUBE_INSECURE}
          - name: HEKETI_KUBE_USER
            value: ${HEKETI_KUBE_USER}
          - name: HEKETI_KUBE_PASSWORD
            value: ${HEKETI_KUBE_PASSWORD}
          - name: HEKETI_KUBE_NAMESPACE
            value: ${HEKETI_KUBE_NAMESPACE}
          - name: HEKETI_KUBE_APIHOST
            value: ${HEKETI_KUBE_APIHOST}
          image: rhgs3/rhgs-volmanager-rhel7
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
          name: heketi
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          volumeMounts:
          - mountPath: /var/lib/heketi
            name: db
        volumes:
        - emptyDir:
          name: db
      strategy:
        type: Recreate
      triggers:
      - type: ConfigChange
parameters:
- description: Set secret for those creating volumes as type _user_
  displayName: Heketi User Secret
  name: HEKETI_USER_KEY
- description: Set secret for administration of the Heketi service as user _admin_
  displayName: Heketi Administrator Secret
  name: HEKETI_ADMIN_KEY
- description: Container path to Kubernetes certificate file
  displayName: Certificate file
  name: HEKETI_KUBE_CERTFILE
- description: Allow insecure SSL/HTTPS access
  displayName: Insecure access
  name: HEKETI_KUBE_INSECURE
  value: "n"
- description: OpenShift/Kubernetes username to access Kubernetes API
  displayName: User
  name: HEKETI_KUBE_USER
  required: true
- description: Password for OpenShift user
  displayName: Password
  name: HEKETI_KUBE_PASSWORD
  required: true
- description: OpenShift project or Kubernetes namespace containing GlusterFS
  displayName: Project/Namespace
  name: HEKETI_KUBE_NAMESPACE
  required: true
- description: 'Kubernetes API host, for example: https://ip:port'
  displayName: API Host Address
  name: HEKETI_KUBE_APIHOST
  required: true