apiVersion: v1
kind: Service
metadata:
  name: qlkube
  labels:
    app: qlkube
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: qlkube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qlkube
  labels:
    app: qlkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qlkube
  template:
    metadata:
      labels:
        app: qlkube
    spec:
      serviceAccountName: qlkube
      containers:
        - name: qlkube
          image: qlkube/qlkube
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qlkube
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qlkube
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: qlkube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qlkube
subjects:
  - kind: ServiceAccount
    name: qlkube
    namespace: default
