apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 10.128.0.11
     iqn: iqn.2012-02.systems.raffa.gc:remotedisk1
     iscsiInterface: tcp
     lun: 0
     fsType: 'ext4'
     readOnly: false