kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rac1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rac2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rac3
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
--- 
apiVersion: v1
kind: Service
metadata:
  name: oracle-rac
  labels:
    app: oracle-rac
spec:
  ports:
  - port: 1521
    name: oracle
  - port: 22
    name: ssh    
  clusterIP: None
  selector:
    app: oracle-rac
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-rac-svc
  labels:
    app: oracle-rac
spec:
  ports:
  - port: 1521
    name: oracle
  selector:
    app: oracle-rac    
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: oracle-rac
spec:
  serviceName: oracle-rac
  replicas: 1
  template:
    metadata:
      labels:
        app: oracle-rac
    spec:
      serviceAccountName: oracle-rac
      volumes:
      - name: rac1
        persistentVolumeClaim:
          claimName: rac1   
      - name: rac2
        persistentVolumeClaim:
          claimName: rac2
      - name: rac3
        persistentVolumeClaim:
          claimName: rac3
      - name: cgroups
        hostPath:
          path: /sys/fs/cgroup
      - name: ssh-secret
        secret:
          secretName: ssh-secret        
      containers:
      - name: oracle-rac
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - SYS_ADMIN
            - NET_ADMIN
        imagePullPolicy: Always
        image: 172.30.243.149:5000/oracle-rac/oracle-rac:latest
        ports:
        - containerPort: 1521
          name: oracle-db
        - containerPort: 22
          name: ssh            
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ORACLE_SID
          value: ORCLCDB
        - name: ORACLE_PDB
          value: ORCLPDB1
        - name: ORACLE_PWD
          value: password
        - name: ORACLE_CHARACTERSET
          value: AL32UTF8
#        livenessProbe:
#          tcpSocket:
#            port: 3306
#          initialDelaySeconds: 30
#          timeoutSeconds: 1
#          periodSeconds: 10
#          successThreshold: 1
#          failureThreshold: 3
#        readinessProbe:
#          exec:
#            command:
#              - "SELECT 1 FROM dual"
#          initialDelaySeconds: 5
#          timeoutSeconds: 1
#          periodSeconds: 10
#          successThreshold: 1
#          failureThreshold: 3
        volumeMounts:
        - name: oracledata
          mountPath: /opt/oracle/oradata
        - name: rac1
          mountPath: /oraclenfs
#        - name: rac2
#          mountPath: /oraclenfs/asm2
#        - name: rac3
#          mountPath: /oraclenfs/asm3
        - name: cgroups
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: ssh-secret
          mountPath: /home/grid/.ssh
#          readOnly: true                                          
  volumeClaimTemplates:
  - metadata:
      name: oracledata
    spec:
#      storageClassName: iscsi
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: scan-forwarder
spec:
  serviceName: scan-forwarder
  replicas: 1
  template:
    metadata:
      labels:
        app: scan-forwarder
    spec:
      containers:
        - name: scan-forwarder
          image: netroby/docker-gotcpforward
          ports:
            - name: scan-port
              containerPort: 1521
          command:
          - "/go/bin/gotcpforward"
          - "-l"
          - ":1521"
          - "-r"
          - oracle-rac-svc:1521  
          imagePullPolicy: "IfNotPresent"
---
apiVersion: v1
kind: Service
metadata:
  name: scan-forwarder
  labels:
    app: scan-forwarder
spec:
  clusterIP: None
  ports:
  - port: 1521
    name: scan-port
  selector:
    app: scan-forwarder           