apiVersion: v1
kind: DeploymentConfig
metadata:
  name: sample-app
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: sample-app
      annotations:
        pod.boostport.com/vault-approle: sample-app
        pod.boostport.com/vault-init-container: install
        pod.alpha.kubernetes.io/init-containers: '[
          {
            "name": "install",
            "image": "boostport/kubernetes-vault-init:0.2.0",
            "env": [
                {
                    "name": "VAULT_ROLE_ID",
                    "value": "e5e8ee7d-ea74-7de0-1c88-8d987a1248a7"
                }
            ],
            "volumeMounts": [
                {
                    "name": "vault-token",
                    "mountPath": "/var/run/secrets/boostport.com"
                }
            ]
          }
        ]'
    spec:
      containers:
      - name: sample-app
        image: boostport/kubernetes-vault-sample-app:0.2.0
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
      volumes:
      - name: vault-token
        emptyDir:
          medium: Memory