apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: vault-controller
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: vault-controller
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: vault-controller
      spec:
        containers:
          - name: vault-controller
            image: "kelseyhightower/vault-controller:0.0.1"
            imagePullPolicy: Always
            env:
              - name: VAULT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: vault-controller
                    key: vault-token
              - name: VAULT_WRAP_TTL
                # The wrapped vault token must unwrapped by the pod in
                # this number of seconds.
                value: "120"
              - name: VAULT_ADDR
                value: "https://vault.vault-controller.svc.cluster.local:8200"
              - name: "VAULT_CACERT"
                value: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"  
              - name: "VAULT_SKIP_VERIFY"
                value: "true"                               
          - name: kubectl
            image: kelseyhightower/kubectl:1.4.0
            args:
              - "proxy"
              - --v=5
              - --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              - --token=/var/run/secrets/kubernetes.io/serviceaccount/token
              - --server=https://kubernetes.default.svc.cluster.local:443 
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: vault-controller
    name: vault-controller
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: vault-controller                       
