apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: <schedule>
  namespace: openshift-adp
spec:
  schedule: "*/60 * * * *"
  template:
    hooks: {}
    includedNamespaces:
    - vm-tests
    storageLocation: dpa-1 
    defaultVolumesToFsBackup: true 
    ttl: 720h0m0s