tenant:
  configSecret:
    name: oadp-env-configuration
    accessKey: oadp 
    secretKey: oadpoadp  
  configuration:
    name: oadp-env-configuration
  name: oadp  
  pools:
    - name: pool-0
      servers: 1
      storageClassName: ontap-nas
      # these values are not recommended in production. They are here just to keep the costs constrained.
      volumesPerServer: 1
      size: 500Gi      
  buckets:
    - name: oadp
      objectLock: false
  certificate:    
    requestAutoCert: false         

                        