apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: nlb
  namespace: openshift-ingress-operator
spec:
  replicas: 2
  domain: nlb.control-cluster-raffa.demo.red-chesterfield.com
  endpointPublishingStrategy: 
    type: "Private"