kind: Service
apiVersion: v1
metadata:
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: '2'
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: '5'
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: '4'
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: '2'
    # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  name: router-nlb
  namespace: openshift-ingress
  labels:
    app: router
    ingresscontroller.operator.openshift.io/owning-ingresscontroller: nlb
    router: router-nlb
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: nlb
  type: LoadBalancer
  externalTrafficPolicy: Local