apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: cert-manager-dns
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - 'route53:ChangeResourceRecordSets'
      - 'route53:GetChange'
      - 'route53:ListHostedZonesByName'
      - 'route53:ListHostedZones'
      effect: Allow
      resource: '*'
  secretRef:
    name: cert-manager-dns-credentials
    namespace: cert-manager