apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: federate
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      interval: 60s
      scrapeTimeout: 30s
      path: /federate
      port: web
      params:
        'match[]':
        - '{namespace=~".+"}'
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        serverName: prometheus-k8s.openshift-monitoring.svc
        #insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - openshift-monitoring
  selector:
    matchLabels:
      prometheus: k8s