host_key_checking: False
ansible_user: openshift
hosting_infrastructure: openstack
# OpenStack Provisioning Variables
# use the "-e" option to set "openstack_ssh_public_key"
#openstack_ssh_public_key:
openstack_default_image_name: "rhel-server-7.6-x86_64"
openstack_default_flavor: "etl1.large"
openstack_external_network_name: "external"
#openstack_dns_domain: "casl.raffa.com"
openstack_subnet_prefix: 192.168.98
openstack_num_masters: 1
openstack_num_nodes: 1
openstack_num_infra: 1
env_id: "raffa2"

dns_domain: "casl-contrib.osp.rht-labs.com"
dns_nameservers:
- 10.9.51.22

openshift_master_api_port: 8443
openshift_master_console_port: 8443

# Sample configuration for the use of DNS servers for name resolution
# NOTE: The view names of `private` and `public` are REQUIRED as it indicates 
#       the role each of these entries have.
#       Each view section can have multiple servers (i.e.: it's a list of servers)

nsupdate_config:
  - view: public
    zone: 'casl-contrib.osp.rht-labs.com'
    server_list:
      - key_secret: 'Xap68yg0yIzeUUAkWZOOspmJC3oj7yXOk3y8GLtPNxc='
        key_algorithm: 'hmac-sha256'
        server: '10.9.51.47'
        key_name: 'external-casl-contrib.osp.rht-labs.com'
  - view: "private"
    zone: 'casl-contrib.osp.rht-labs.com'
    server_list:
      - key_secret: 'Hhb4i8lxFZ32MEj/tjcHCukw2vjtQh3RXmw4A5Fd/Lg='
        key_algorithm: 'hmac-sha256'
        key_name: 'internal-casl-contrib.osp.rht-labs.com'
        server: '10.9.51.22'

openstack_lb_flavor: m1.small
openstack_etcd_flavor: m1.large
openstack_master_flavor: m1.large
openstack_node_flavor: etl1.medium
openstack_infra_flavor: etl1.medium
openstack_dns_flavor: m1.small



docker_volume_size: "10"
docker_storage_block_device: "/dev/vdb"
docker_storage_mount_point: "/var/lib/containers/docker"


openshift_hosted_registry_storage_kind: openstack


rhsm_repos:
 - "rhel-7-server-rpms"
 - "rhel-7-server-ose-3.11-rpms"
 - "rhel-7-server-extras-rpms"
 - "rhel-7-fast-datapath-rpms"
 - "rhel-7-server-optional-rpms"
 - "rhel-7-server-ansible-2.6-rpms"
 - "rhel-7-server-openstack-13-rpms"
 - "rhel-7-server-openstack-13-tools-rpms" 
 
 
rhsm_username: "{{ lookup('env','RHN_USERNAME') }}"
rhsm_password: "{{ lookup('env','RHN_PASSWORD') }}"
rhsm_register: true
rhsm_pool: "{{ lookup('env','RHN_SUB_POOL') }}"




