kind: Deployment
apiVersion: apps/v1
metadata:
  name: tvk-console-plugin
  labels:
    app: tvk-console-plugin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tvk-console-plugin
  template:
    metadata:
      labels:
        app: tvk-console-plugin
    spec:
      volumes:
        - name: tvk-console-plugin-cert
          secret:
            secretName: tvk-console-plugin-cert
            defaultMode: 420
        - name: nginx-conf
          configMap:
            name: tvk-console-plugin
            defaultMode: 420
      containers:
        - resources:
            requests:
              cpu: 10m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          name: tvk-console-plugin
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 9443
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: tvk-console-plugin-cert
              readOnly: true
              mountPath: /var/cert
            - name: nginx-conf
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          terminationMessagePolicy: File
          image: 'eu.gcr.io/triliovault/tvk-console-plugin:v3.0.2'
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

