kind: Service
apiVersion: v1
metadata:
  name: tvk-console-plugin
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: tvk-console-plugin-cert
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  type: ClusterIP
  selector:
    app: tvk-console-plugin