kind: Secret
apiVersion: v1
metadata:
  name: triliovault-dex
  labels:
    triliovault.trilio.io/secret: triliovault-dex
stringData:
  TVK_DEX_CONFIG: |
    connectors:
    - id: openshift
      name: Openshift
      type: openshift
      config:
        issuer: https://kubernetes.default.svc.cluster.local
        clientID: trilioclient
        clientSecret: ciaociao
        redirectURI: https://trilio-system.apps.${CLUSTER_BASE_DOMAIN}/dex/callback
        insecureCA: true
type: Opaque