apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: minio-operator
spec:
  upgradeStrategy: Default
---  
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "minio-operator" 
spec:
    channel: stable
    installPlanApproval: Automatic
    name: minio-operator
    source: certified-operators
    sourceNamespace: openshift-marketplace
