apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: ovn-kubernetes-l2-nosub
  name: ovn-kubernetes-l2-nosub
  namespace: test-ovn
spec:
  config: |
    {
      "name": "ovn-kubernetes-l2-nosub",
      "type": "ovn-k8s-cni-overlay",
      "cniVersion": "0.3.1",
      "topology": "layer2",
      "netAttachDefName": "test-ovn/ovn-kubernetes-l2-nosub"
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: test-ovn-kubernetes-l2-nosub
  namespace: test-ovn
  annotations:
    k8s.v1.cni.cncf.io/networks: ovn-kubernetes-l2-nosub
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
  restartPolicy: "Never"
  automountServiceAccountToken: false
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: ovn-kubernetes-l2-nosub-ipam
  name: ovn-kubernetes-l2-nosub-ipam
  namespace: test-ovn
spec:
  config: |
    {
      "name": "ovn-kubernetes-l2-nosub-ipam",
      "type": "ovn-k8s-cni-overlay",
      "cniVersion": "0.3.1",
      "topology": "layer2",
      "netAttachDefName": "test-ovn/ovn-kubernetes-l2-nosub-ipam",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.2.0/24",
        "rangeStart": "192.168.2.200",
        "rangeEnd": "192.168.2.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.2.1"
      }      
    }    
---
apiVersion: v1
kind: Pod
metadata:
  name: test-ovn-kubernetes-l2-nosub-ipam
  namespace: test-ovn
  annotations:
    k8s.v1.cni.cncf.io/networks: ovn-kubernetes-l2-nosub-ipam
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
  restartPolicy: "Never"
  automountServiceAccountToken: false
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: ovn-kubernetes-l2-sub
  name: ovn-kubernetes-l2-sub
  namespace: test-ovn
spec:
  config: |
    {
      "name": "ovn-kubernetes-l2-sub",
      "type": "ovn-k8s-cni-overlay",
      "cniVersion": "0.3.1",
      "topology": "layer2",
      "netAttachDefName": "test-ovn/ovn-kubernetes-l2-sub",
      "subnets": "192.168.100.0/24,2001:DBB::/64"
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: test-ovn-kubernetes-l2-sub
  namespace: test-ovn
  annotations:
    k8s.v1.cni.cncf.io/networks: ovn-kubernetes-l2-sub
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
  restartPolicy: "Never"
  automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  name: test-ovn-kubernetes-l2-sub-2
  namespace: test-ovn
  annotations:
    k8s.v1.cni.cncf.io/networks: ovn-kubernetes-l2-sub
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
  restartPolicy: "Never"
  automountServiceAccountToken: false
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: ovn-kubernetes-l2-sub-vrf
  name: ovn-kubernetes-l2-sub-vrf
  namespace: test-ovn
spec:
  config: |
    {
      "name": "ovn-kubernetes-l2-sub-vrf",
      "cniVersion": "0.3.1",
      "plugins":
      [{
        "type": "ovn-k8s-cni-overlay",
        "topology": "layer2",
        "netAttachDefName": "test-ovn/ovn-kubernetes-l2-sub-vrf",
        "subnets": "192.168.100.0/24,2001:DBB::/64"
      },
      {
        "type": "vrf", 
        "vrfname": "vrf-1",  
        "table": 1001   
      }]
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: test-ovn-kubernetes-l2-sub-vrf
  namespace: test-ovn
  annotations:
    k8s.v1.cni.cncf.io/networks: ovn-kubernetes-l2-sub-vrf
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
  restartPolicy: "Never"
  automountServiceAccountToken: false
    

