apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ${infra_id}
  name: ${infra_id}-es-${az}
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ${infra_id}
      machine.openshift.io/cluster-api-machine-role: es
      machine.openshift.io/cluster-api-machine-type: es
      machine.openshift.io/cluster-api-machineset: ${infra_id}-es-${az}
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ${infra_id}
        machine.openshift.io/cluster-api-machine-role: es
        machine.openshift.io/cluster-api-machine-type: es
        machine.openshift.io/cluster-api-machineset: ${infra_id}-es-${az}
    spec:
      taints:
      - key: node-role.kubernetes.io/es
        effect: NoSchedule
      metadata:
        labels:
          node-role.kubernetes.io/es: es
      providerSpec:
        value:
          ami:
            id: ami-00745fcbb14a863ed
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 120
              volumeType: gp2
          - ebs:
              iops: 0
              volumeSize: 200
              volumeType: gp2
#            deviceName: /dev/rook                
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ${infra_id}-worker-profile
          instanceType: m5.xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: ${az}
            region: ${region}
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - ${infra_id}-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - ${infra_id}-private-${az}
          tags:
          - name: kubernetes.io/cluster/${infra_id}
            value: owned
          userDataSecret:
            name: worker-user-data