kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: aggregate-grafana-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true" 
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true" 
rules:
- apiGroups:
  - "integreatly.org"
  resources:
  - grafanas
  - grafanas/status
  - grafanas/finalizers
  - grafanadashboards
  - grafanadashboards/status
  - grafanadatasources
  - grafanadatasources/status
  verbs:
  - "get"
  - "list"
  - "watch"
