apiVersion: v1
kind: Secret
metadata:
  name: ontap-san-secret
type: Opaque
stringData:
  username: labadmin
  password: ocpvirt01!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: ontap-san
spec:
  version: 1
  storageDriverName: ontap-san
  managementLIF: netapp.etl.rht-labs.com
  svm: ocp_e4
  credentials: 
    name: ontap-san-secret
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-san
  annotations:
    storageclass.kubevirt.io/is-default-virt-class: "true"
provisioner: csi.trident.netapp.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  backendType: "ontap-san"
  provisioningType: "thin"
  snapshots: "true"     
  clones: "true"