apiVersion: v1
kind: Secret
metadata:
  name: ontap-nas-secret
type: Opaque
stringData:
  username: labadmin
  password: ocpvirt01!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: ontap-nas
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: netapp.etl.rht-labs.com
  dataLIF: nfs1.etl.rht-labs.com
  backendName: ontap-nas
  svm: nfs_02
  autoExportPolicy: true
  credentials: 
    name: ontap-nas-secret
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-nas
  annotations: 
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  backendType: "ontap-nas"
  provisioningType: "thin"
  snapshots: "true"  
  clones: "true"  