apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: external-dns
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - route53:ChangeResourceRecordSets
      effect: Allow
      resource: arn:aws:route53:::hostedzone/*      
    - action:
      - "route53:ListHostedZones"
      - "route53:ListResourceRecordSets"
      effect: Allow
      resource: '*'
  secretRef:
    name: external-dns-aws-kms-credentials
    namespace: ${namespace}