provider: aws
aws:
  zoneType: public
sources:
  - openshift-route
  - crd
logLevel: debug
annotationFilter: route-type=global
txtPrefix: ocp
crd:
  create: true
  apiversion: externaldns.k8s.io/v1alpha1
  kind: DNSEndpoint
  