---
apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: ${namespace}
spec:
  domain: ${namespace}.${cluster_base_domain}
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: ${namespace}
  namespace: openshift-ingress-operator
spec:
  domain: ${namespace}.${cluster_base_domain}
  routeSelector:
    matchLabels:
      route-type: global
      router: ${namespace}       